services:
  meili:
    image: getmeili/meilisearch
    container_name: meilisearch
    ports:
      - "7700:7700"
    volumes:
      - './meili_data:/meili_data'
    environment:
      - MEILI_MASTER_KEY=yHx0xwwnFxoGEDs5jMAt
    restart: unless-stopped